<?php

namespace Database\Seeders;

use App\Models\TenagaKerja;
use App\Models\UnitLayanan;
use App\Models\Sertifikasi;
use Illuminate\Database\Seeder;

class TenagaKerjaSeeder extends Seeder
{
    public function run(): void
    {
        $unitMap = UnitLayanan::pluck('id', 'kode')->toArray();

        $workers = [
            [
                'no_urut' => '01',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'SUGENG',
                'nik' => '3502011706820001',
                'tempat_lahir' => 'PONOROGO',
                'tanggal_lahir' => '1982-06-17',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'LISTRIK INSTALASI',
                'no_telepon' => '0813-5978-8537',
                'email' => 'sugeng.yantek@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Dukuh Krajan RT:02/01 Jebeng Slahung',
                'kota_kabupaten' => 'PONOROGO',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'SPV YANTEK BAGIAN PEMELIHARAAN',
                'fungsi_pekerjaan' => 'Pemeliharaan Distribusi',
                'unit' => 'UP3 PONOROGO',
                'unit_layanan_id' => $unitMap['UP3_PONOROGO'] ?? null,
                'nomor_bpjs_kesehatan' => '0001139769213',
                'nomor_bpjs_ketenagakerjaan' => '19046340527',
                'nomor_dplk' => '810367088452',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '009/APP/PON/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => [
                    [
                        'nomor_sertifikat' => 'SERT-YTK-2024-0891',
                        'judul_sertifikasi' => 'Kompetensi Pemeliharaan Jaringan Tegangan Rendah & Menengah (K3)',
                        'tanggal_terbit' => '2024-02-15',
                    ]
                ]
            ],
            [
                'no_urut' => '02',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'AGUS PRASETYO',
                'nik' => '3502041203870002',
                'tempat_lahir' => 'TRENGGALEK',
                'tanggal_lahir' => '1987-03-12',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'TEKNIK KETENAGALISTRIKAN',
                'no_telepon' => '0812-3344-9812',
                'email' => 'agus.prasetyo@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Jl. Panglima Sudirman No. 45, Trenggalek',
                'kota_kabupaten' => 'TRENGGALEK',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'PELAKSANA OPERASI & HAR DISTRIBUSI',
                'fungsi_pekerjaan' => 'Operasi & Har',
                'unit' => 'ULP TRENGGALEK',
                'unit_layanan_id' => $unitMap['TRENGGALEK'] ?? null,
                'nomor_bpjs_kesehatan' => '0001248956124',
                'nomor_bpjs_ketenagakerjaan' => '20057451638',
                'nomor_dplk' => '810367088563',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '012/APP/TRG/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => [
                    [
                        'nomor_sertifikat' => 'K3-DIST-2023-0112',
                        'judul_sertifikasi' => 'Sertifikat K3 Ketenagalistrikan Tingkat Lanjut',
                        'tanggal_terbit' => '2023-08-10',
                    ]
                ]
            ],
            [
                'no_urut' => '03',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'BAMBANG HERMAWAN',
                'nik' => '3501021405900003',
                'tempat_lahir' => 'PACITAN',
                'tanggal_lahir' => '1990-05-14',
                'pendidikan_terakhir' => 'SMA',
                'jurusan' => 'IPA',
                'no_telepon' => '0821-4455-6677',
                'email' => 'bambang.hermawan@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Dusun Krajan, Desa Arjowinangun, Pacitan',
                'kota_kabupaten' => 'PACITAN',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'REGU RABAS / TEBANG POHON DISTRIBUSI',
                'fungsi_pekerjaan' => 'Right of Way (ROW)',
                'unit' => 'ULP PACITAN',
                'unit_layanan_id' => $unitMap['PACITAN'] ?? null,
                'nomor_bpjs_kesehatan' => '0001359067235',
                'nomor_bpjs_ketenagakerjaan' => '21068562749',
                'nomor_dplk' => '810367088674',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '034/APP/PCT/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => []
            ],
            [
                'no_urut' => '04',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'DWI CAHYONO',
                'nik' => '3502082208850001',
                'tempat_lahir' => 'PONOROGO',
                'tanggal_lahir' => '1985-08-22',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'ELEKTRONIKA INDUSTRI',
                'no_telepon' => '0813-7788-9900',
                'email' => 'dwi.cahyono@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Jl. Ki Ageng Kutu No. 12, Siman, Ponorogo',
                'kota_kabupaten' => 'PONOROGO',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'PETUGAS PENANGANAN GANGGUAN (YANTEK)',
                'fungsi_pekerjaan' => 'Pelayanan Teknik',
                'unit' => 'ULP BALONG',
                'unit_layanan_id' => $unitMap['BALONG'] ?? null,
                'nomor_bpjs_kesehatan' => '0001460178346',
                'nomor_bpjs_ketenagakerjaan' => '22079673850',
                'nomor_dplk' => '810367088785',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '045/APP/BLG/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => [
                    [
                        'nomor_sertifikat' => 'YTK-TR-2022-0451',
                        'judul_sertifikasi' => 'Sertifikasi Operator Gardu Distribusi',
                        'tanggal_terbit' => '2022-11-04',
                    ]
                ]
            ],
            [
                'no_urut' => '05',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'EKO WAHYUDI',
                'nik' => '3502030511920005',
                'tempat_lahir' => 'PONOROGO',
                'tanggal_lahir' => '1992-11-05',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'TEKNIK MESIN OTOMOTIF',
                'no_telepon' => '0857-1122-3344',
                'email' => 'eko.wahyudi@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Desa Jenangan RT:01/02, Ponorogo',
                'kota_kabupaten' => 'PONOROGO',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'DRIVER MOBIL GANGGUAN / YANTEK',
                'fungsi_pekerjaan' => 'Armada Reaksi Cepat',
                'unit' => 'ULP PONOROGO',
                'unit_layanan_id' => $unitMap['PONOROGO'] ?? null,
                'nomor_bpjs_kesehatan' => '0001571289457',
                'nomor_bpjs_ketenagakerjaan' => '23080784961',
                'nomor_dplk' => '810367088896',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '056/APP/PNG/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => []
            ],
            [
                'no_urut' => '06',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'SITI NURHALIZA',
                'nik' => '3502015509960002',
                'tempat_lahir' => 'PONOROGO',
                'tanggal_lahir' => '1996-09-15',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'SISTEM INFORMASI',
                'no_telepon' => '0812-9988-7766',
                'email' => 'siti.nurhaliza@gmail.com',
                'jenis_kelamin' => 'PEREMPUAN',
                'alamat_domisili' => 'Jl. Sultan Agung No. 88, Ponorogo',
                'kota_kabupaten' => 'PONOROGO',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'ADMINISTRASI TEKNIK & ARSIP YANTEK',
                'fungsi_pekerjaan' => 'Administrasi Distribusi',
                'unit' => 'UP3 PONOROGO',
                'unit_layanan_id' => $unitMap['UP3_PONOROGO'] ?? null,
                'nomor_bpjs_kesehatan' => '0001682390568',
                'nomor_bpjs_ketenagakerjaan' => '24091895072',
                'nomor_dplk' => '810367089007',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '067/APP/PON/ADM-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWT',
                'skema_tenaga_kerja' => 'VOLUME BASED',
                'sertifikasi' => [
                    [
                        'nomor_sertifikat' => 'BNSP-ADM-2023-789',
                        'judul_sertifikasi' => 'Sertifikasi BNSP Administrasi Perkantoran Profesional',
                        'tanggal_terbit' => '2023-05-20',
                    ]
                ]
            ],
            [
                'no_urut' => '07',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'HENDRA KURNIAWAN',
                'nik' => '3502061004890001',
                'tempat_lahir' => 'TRENGGALEK',
                'tanggal_lahir' => '1989-04-10',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'LISTRIK',
                'no_telepon' => '0822-6677-8899',
                'email' => 'hendra.kurniawan@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Dsn. Gendingan, Gandusari, Trenggalek',
                'kota_kabupaten' => 'TRENGGALEK',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'TEKNISI PENGGANTIAN ISOLATOR TM',
                'fungsi_pekerjaan' => 'Pemeliharaan TM/TR',
                'unit' => 'ULP TRENGGALEK',
                'unit_layanan_id' => $unitMap['TRENGGALEK'] ?? null,
                'nomor_bpjs_kesehatan' => '0001793401679',
                'nomor_bpjs_ketenagakerjaan' => '25102906183',
                'nomor_dplk' => '810367089118',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '078/APP/TRG/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => []
            ],
            [
                'no_urut' => '08',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'RUDI SETIAWAN',
                'nik' => '3501050807910002',
                'tempat_lahir' => 'PACITAN',
                'tanggal_lahir' => '1991-07-08',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'TEKNIK BANGUNAN',
                'no_telepon' => '0878-5544-3322',
                'email' => 'rudi.setiawan@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Jl. Gatot Subroto No. 34, Pacitan',
                'kota_kabupaten' => 'PACITAN',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'PELAKSANA PENGUKURAN TEGANGAN UJUNG',
                'fungsi_pekerjaan' => 'Kualitas Daya',
                'unit' => 'ULP PACITAN',
                'unit_layanan_id' => $unitMap['PACITAN'] ?? null,
                'nomor_bpjs_kesehatan' => '0001904512780',
                'nomor_bpjs_ketenagakerjaan' => '26113017294',
                'nomor_dplk' => '810367089229',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '089/APP/PCT/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => []
            ],
            [
                'no_urut' => '09',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'JOKO SUSILO',
                'nik' => '3502091402840001',
                'tempat_lahir' => 'PONOROGO',
                'tanggal_lahir' => '1984-02-14',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'LISTRIK',
                'no_telepon' => '0813-2233-4455',
                'email' => 'joko.susilo@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Dukuh Krajan, Jetis, Ponorogo',
                'kota_kabupaten' => 'PONOROGO',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'SPV REGU 1 YANTEK BALONG',
                'fungsi_pekerjaan' => 'Pelayanan Teknik',
                'unit' => 'ULP BALONG',
                'unit_layanan_id' => $unitMap['BALONG'] ?? null,
                'nomor_bpjs_kesehatan' => '0002015623891',
                'nomor_bpjs_ketenagakerjaan' => '27124128305',
                'nomor_dplk' => '810367089330',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '092/APP/BLG/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => [
                    [
                        'nomor_sertifikat' => 'K3-SPV-2023-0982',
                        'judul_sertifikasi' => 'Pengawas Keselamatan Kerja K3 Bidang Transmisi & Distribusi',
                        'tanggal_terbit' => '2023-09-12',
                    ]
                ]
            ],
            [
                'no_urut' => '10',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'ANITA WULANDARI',
                'nik' => '3502016012970003',
                'tempat_lahir' => 'PONOROGO',
                'tanggal_lahir' => '1997-12-20',
                'pendidikan_terakhir' => 'D3',
                'jurusan' => 'MANAJEMEN INFORMATIKA',
                'no_telepon' => '0857-4433-2211',
                'email' => 'anita.wulandari@gmail.com',
                'jenis_kelamin' => 'PEREMPUAN',
                'alamat_domisili' => 'Jl. Budi Utomo No. 56, Ponorogo',
                'kota_kabupaten' => 'PONOROGO',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'ADMINISTRASI LOGISTIK MATERIAL',
                'fungsi_pekerjaan' => 'Logistik & Gudang',
                'unit' => 'ULP PONOROGO',
                'unit_layanan_id' => $unitMap['PONOROGO'] ?? null,
                'nomor_bpjs_kesehatan' => '0002126734902',
                'nomor_bpjs_ketenagakerjaan' => '28135239416',
                'nomor_dplk' => '810367089441',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '098/APP/PNG/LOG-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWT',
                'skema_tenaga_kerja' => 'VOLUME BASED',
                'sertifikasi' => []
            ],
            [
                'no_urut' => '11',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'M. IRFAN MAULANA',
                'nik' => '3502051809930002',
                'tempat_lahir' => 'TRENGGALEK',
                'tanggal_lahir' => '1993-09-18',
                'pendidikan_terakhir' => 'SMK',
                'jurusan' => 'TEKNIK KELISTRIKAN',
                'no_telepon' => '0812-8876-1234',
                'email' => 'irfan.maulana@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Ds. Durenan, Trenggalek',
                'kota_kabupaten' => 'TRENGGALEK',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'TEKNISI RECLOSER & SECTIONALIZER',
                'fungsi_pekerjaan' => 'Proteksi Distribusi',
                'unit' => 'ULP TRENGGALEK',
                'unit_layanan_id' => $unitMap['TRENGGALEK'] ?? null,
                'nomor_bpjs_kesehatan' => '0002127836453',
                'nomor_bpjs_ketenagakerjaan' => '29127836456',
                'nomor_dplk' => '810367089375',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '105/APP/TRG/YTK-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => []
            ],
            [
                'no_urut' => '12',
                'nomor_perjanjian' => '1211,Pj/DAN,00,07/F04000000/2024',
                'nama_perusahaan' => 'PT ANUGERAH PUTRA PERMANA',
                'nama' => 'WAHYU TRI PRASETYA',
                'nik' => '3501032506880004',
                'tempat_lahir' => 'PACITAN',
                'tanggal_lahir' => '1988-06-25',
                'pendidikan_terakhir' => 'D3',
                'jurusan' => 'TEKNIK ELEKTRO',
                'no_telepon' => '0853-2219-0091',
                'email' => 'wahyu.tri@gmail.com',
                'jenis_kelamin' => 'LAKI',
                'alamat_domisili' => 'Jl. WR Supratman, Pacitan',
                'kota_kabupaten' => 'PACITAN',
                'provinsi' => 'JAWA TIMUR',
                'jabatan_terakhir' => 'INSPEKTUR K3 & LINGKUNGAN',
                'fungsi_pekerjaan' => 'K3 Distribusi',
                'unit' => 'ULP PACITAN',
                'unit_layanan_id' => $unitMap['PACITAN'] ?? null,
                'nomor_bpjs_kesehatan' => '0002238947564',
                'nomor_bpjs_ketenagakerjaan' => '30138947567',
                'nomor_dplk' => '810367089486',
                'bank_dplk' => 'BNI',
                'no_perjanjian_kerja' => '118/APP/PCT/K3-MDN/2024',
                'tanggal_masuk_kerja' => '2024-01-01',
                'status_tenaga_kerja' => 'PKWTT',
                'skema_tenaga_kerja' => 'PEMBORONGAN',
                'sertifikasi' => [
                    [
                        'nomor_sertifikat' => 'AH-K3-LISTRIK-2023-402',
                        'judul_sertifikasi' => 'Ahli K3 Bidang Listrik Kemnaker RI',
                        'tanggal_terbit' => '2023-07-22',
                    ]
                ]
            ]
        ];

        foreach ($workers as $w) {
            $sertifikasiList = $w['sertifikasi'] ?? [];
            unset($w['sertifikasi']);

            $tk = TenagaKerja::updateOrCreate(['nik' => $w['nik']], $w);

            foreach ($sertifikasiList as $cert) {
                Sertifikasi::updateOrCreate(
                    [
                        'tenaga_kerja_id' => $tk->id,
                        'nomor_sertifikat' => $cert['nomor_sertifikat']
                    ],
                    $cert
                );
            }
        }
    }
}
